# Generated by Django 6.0.5 on 2026-05-29 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('codi_nacional', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nom_comercial', models.CharField(max_length=150)),
                ('principi_actiu', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=60)),
                ('cognoms', models.CharField(max_length=150)),
                ('data_naixement', models.DateField()),
                ('telefon', models.CharField(max_length=20)),
                ('adreca', models.CharField(max_length=200)),
                ('correu', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tractament',
            fields=[
                ('codi_tractament', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('data_inici', models.DateField()),
                ('data_fi_prevista', models.DateField()),
                ('indicacions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metge',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestio_medica.persona')),
                ('num_collegiat', models.CharField(max_length=15, unique=True)),
            ],
            bases=('gestio_medica.persona',),
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestio_medica.persona')),
            ],
            bases=('gestio_medica.persona',),
        ),
        migrations.CreateModel(
            name='Prescripcio',
            fields=[
                ('codi_prescripcio', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('dosi', models.CharField(max_length=60)),
                ('frequencia', models.CharField(max_length=60)),
                ('durada', models.CharField(max_length=60)),
                ('estat', models.CharField(max_length=20)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestio_medica.medicament')),
                ('tractament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestio_medica.tractament')),
            ],
        ),
    ]
