# Generated by Django 6.0.5 on 2026-05-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_medica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicament',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='metge',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pacient',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prescripcio',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tractament',
            options={'managed': False},
        ),
    ]
