# Generated by Django 6.0.5 on 2026-05-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_medica', '0002_alter_medicament_options_alter_metge_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicament',
            table='medicament',
        ),
        migrations.AlterModelTable(
            name='metge',
            table='metge',
        ),
        migrations.AlterModelTable(
            name='pacient',
            table='pacient',
        ),
        migrations.AlterModelTable(
            name='persona',
            table='persona',
        ),
        migrations.AlterModelTable(
            name='prescripcio',
            table='prescripcio',
        ),
        migrations.AlterModelTable(
            name='tractament',
            table='tractament',
        ),
    ]
