# Generated by Django 6.0.5 on 2026-06-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_medica', '0003_alter_medicament_table_alter_metge_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('codi_diagnostic', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('descripcio', models.TextField()),
                ('notes_cliniques', models.TextField(blank=True, null=True)),
                ('codi_cita', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'diagnostic',
                'managed': False,
            },
        ),
    ]
