# Generated by Django 6.0.5 on 2026-06-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_medica', '0004_diagnostic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('codi_cita', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('estat', models.CharField(choices=[('pendent', 'pendent'), ('confirmada', 'confirmada'), ('finalitzada', 'finalitzada'), ('cancelada', 'cancelada')], max_length=50)),
                ('dni_pacient', models.CharField(max_length=9)),
                ('codi_centre', models.CharField(max_length=15)),
                ('codi_sala', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'cita',
                'managed': False,
            },
        ),
    ]
