# Generated by Django 6.0.5 on 2026-06-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_medica', '0005_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinic',
            fields=[
                ('codi_historial', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('grup_sanguini', models.CharField(blank=True, max_length=3, null=True)),
                ('antecedents', models.TextField(blank=True, null=True)),
                ('malalties_croniques', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historial_clinic',
                'managed': False,
            },
        ),
    ]
