# Generated by Django 6.0.5 on 2026-06-11 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_medica', '0006_historialclinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreMedic',
            fields=[
                ('codi_centre', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('carrer', models.CharField(blank=True, max_length=200, null=True)),
                ('codi_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('ciutat', models.CharField(blank=True, max_length=100, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'centremedic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiagnosticMalaltia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'diagnosticmalaltia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dispensacio',
            fields=[
                ('codi_dispensacio', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('data_lliurament', models.DateField()),
                ('quantitat_dispensada', models.IntegerField()),
                ('codi_tractament', models.CharField(max_length=15)),
                ('codi_nacional', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'dispensacio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Malaltia',
            fields=[
                ('codi_cie', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('descripcio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'malaltia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supervisio',
            fields=[
                ('dni_supervisor', models.ForeignKey(db_column='supervisor_dni', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='supervisats', serialize=False, to='gestio_medica.metge')),
            ],
            options={
                'db_table': 'supervisio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Torn',
            fields=[
                ('codi_torn', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('dia_setmana', models.CharField(max_length=20)),
                ('hora_inici', models.TimeField()),
                ('hora_fi', models.TimeField()),
                ('data_inici', models.DateField()),
                ('data_fi', models.DateField()),
            ],
            options={
                'db_table': 'torn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('codi_usuari', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('contrasenya', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuari',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='historialclinic',
            table='historialclinic',
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('codi_centre', models.OneToOneField(db_column='codi_centre', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='farmacia', serialize=False, to='gestio_medica.centremedic')),
            ],
            options={
                'db_table': 'farmacia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstocMedicament',
            fields=[
                ('codi_centre', models.ForeignKey(db_column='codi_centre', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='estoc', serialize=False, to='gestio_medica.farmacia')),
                ('quantitat_disponible', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'estocmedicament',
                'managed': False,
            },
        ),
    ]
