# Generated by Django 6.0.5 on 2026-06-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_medica', '0006_historialclinic'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historialclinic',
            table='historialclinic',
        ),
    ]
